🔹 Step 1: Environment Setup

In [124]:
# Install required libraries (run once)
# pip install pandas numpy matplotlib scikit-learn tensorflow

In [125]:
!python --version

Python 3.12.12

🔹 Step 2: Import Libraries

In [126]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, Input, Bidirectional
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.callbacks import EarlyStopping

🔹 Step 3: Load & Inspect Dataset

In [127]:
df = pd.read_csv("Job_3_Resource_sentiment.csv")
print(df.columns)

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [128]:
df.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [129]:
df.columns

Index(['2401', 'Borderlands', 'Positive',
       'im getting on borderlands and i will murder you all ,'],
      dtype='object')

In [130]:
df.rename(columns={'Positive': 'sentiment'}, inplace=True)
df.rename(columns={'im getting on borderlands and i will murder you all ,': 'text'}, inplace=True)

In [131]:
df.columns

Index(['2401', 'Borderlands', 'sentiment', 'text'], dtype='object')

In [132]:
df.sample(5)

,2401,Borderlands,sentiment,text
73772,9039,Nvidia,Irrelevant,"Apple is the no for me, they don’t innovate an..."
37304,8397,Microsoft,Neutral,"CNET - <unk> Duo may change the world, or it c..."
36743,8304,Microsoft,Negative,microsoft are SHIT pic.twitter.com/893nuCUYrV
6946,395,Amazon,Negative,Aye Amazon and running shit lmfao bullying con...
8533,9464,Overwatch,Positive,Hello! What's today's fortune. [It will be a w...

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   2401         74681 non-null  int64
 1   Borderlands  74681 non-null  object
 2   sentiment    74681 non-null  object
 3   text         73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB

In [134]:
df = df[['text', 'sentiment']]

In [135]:
df.sample(5)

                                                    text   sentiment
31610                                    @vgdunkey<unk>.  Irrelevant
11809  Kobe We Miss You (N2k Do The Right Thing!!) yo...    Positive
3818   RhandlerR The Call of Duty: Black Ops Cold War...    Negative
21554  Tbh valorant is csgo on ez mode this is like m...  Irrelevant
22432  open game is objectively the worst valve game ...  Irrelevant

In [136]:
df

                                                    text sentiment
0      I am coming to the borders and I will kill you...  Positive
1      im getting on borderlands and i will kill you ...  Positive
2      im coming on borderlands and i will murder you...  Positive
3      im getting on borderlands 2 and i will murder ...  Positive
4      im getting into borderlands and i can murder y...  Positive
...                                                  ...       ...
74676  Just realized that the Windows partition of my...  Positive
74677  Just realized that my Mac window partition is ...  Positive
74678  Just realized the windows partition of my Mac ...  Positive
74679  Just realized between the windows partition of...  Positive
74680  Just like the windows partition of my Mac is l...  Positive

[74681 rows x 2 columns]

In [137]:
df.shape

(74681, 2)

In [138]:
df.isnull().sum()

text         686
sentiment      0
dtype: int64

In [139]:
print(df['sentiment'].value_counts())

sentiment
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [140]:
df.duplicated().sum()

np.int64(4909)